base_url = "https://blog.codewars.com"
title = "The Codewars Blog"
description = ""
default_language = "en"

compile_sass = false
build_search_index = false
generate_feed = true
feed_filename = "rss.xml"

taxonomies = [
  { name = "tags", paginate_by = 5, feed = true },
]

[markdown]
highlight_code = true
highlight_theme = "one-dark"

[extra]
